In [2]:
my_list =[1,2,3]


In [3]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat =[[2,3,4],[5,6,7],[8,9,0]]


In [7]:
np.array(my_mat)

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [8]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(2)

array([1., 1.])

In [14]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.random.rand(4)

array([0.4529945 , 0.41533326, 0.55030954, 0.63919807])

In [17]:
np.random.rand(3,3)

array([[0.72348733, 0.78486144, 0.10364708],
       [0.08460663, 0.02763965, 0.47726711],
       [0.97118561, 0.33649191, 0.10317223]])

In [18]:
np.random.randn(3)

array([0.63714722, 1.58794174, 0.59399303])

In [19]:
np.random.randn(5,5)

array([[-0.00437069, -0.59220722, -0.0478637 ,  0.50296029, -0.48572916],
       [-0.26013359, -0.93491334,  0.46730546, -1.97583403, -0.10166833],
       [-0.11266019, -0.44291075, -1.23488568,  0.90296383,  0.78787108],
       [ 0.32288634, -0.48609634,  0.13816081,  0.43813187,  1.39545233],
       [-1.04558967,  0.53879218,  1.39776216,  1.13629393,  0.05713345]])

In [20]:
np.random.randint(1,100,10)

array([50, 19, 54,  6, 84, 85, 41, 72, 19, 16])

In [21]:
arr=np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr=np.random.randint(0,50,10)

In [24]:
ranarr

array([25, 18, 44, 38, 22, 45,  6,  9, 20,  0])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr

array([25, 18, 44, 38, 22, 45,  6,  9, 20,  0])

In [27]:
ranarr.max()

45

In [28]:
ranarr.max()

45

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmax()

5

In [31]:
ranarr.argmin()

9

In [32]:
arr.shape

(25,)

In [33]:
arr=arr.reshape(5,5)

In [34]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
from numpy.random import randint

In [38]:
randint(2,10)

2

In [39]:
arr=np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
arr[7:]

array([ 7,  8,  9, 10])

In [45]:
arr[0:5]=100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr=np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
slice_of_arr=arr[1:7]

In [50]:
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [51]:
slice_of_arr=arr[:7]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5, 6])

In [53]:
slice_of_arr[:]=99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [56]:
arr_copy=arr.copy()

In [57]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [58]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [59]:
arr_copy[:]=100

In [60]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
arr

array([99, 99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [62]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [63]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr_2d[0][0]

1

In [65]:
arr_2d[1][1]

5

In [66]:
arr_2d[1]

array([4, 5, 6])

In [67]:
arr_2d[2][0]

7

In [68]:
arr_2d[2,0]

7

In [69]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [70]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr=np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [74]:
bool_arr=arr>5

In [75]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [76]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr<7]

array([1, 2, 3, 4, 5, 6])

In [79]:
arr_2d=np.arange(50).reshape(5,10)

In [80]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[2:4,4:6]

array([[24, 25],
       [34, 35]])

In [84]:
arr=np.arange(0,10)

In [85]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [89]:
arr+200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209])

In [90]:
arr*100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [91]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [92]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
1/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [94]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [98]:
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])